services:
  emby-register:
    image: unclesamo/emby-register-brutalist:latest
    platform: linux/amd64
    container_name: emby-register-brutalist
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_SECRET_KEY=d8ea61b70a3257f7b334ef4c26b71de65a4459a3a6182a191debbbf09fb2f0dd
      - ADMIN_PASSWORD=piggo.register
      - EMBY_SERVER_URL=https://ee.vim.im
      - EMBY_API_KEY=b73252c004134cd889031eb171505c3b
      - COPY_FROM_USER_ID=c2ea1659c6eb4dc88a6e8a9757dcb618
      - PUBLIC_ACCESS_URL=https://reg.vim.im
      # --- Optional: Moviepilot Integration ---
      # To enable, uncomment and set the following variables.
      # The option to create a Moviepilot user will appear on the registration page.
      - MOVIEPILOT_URL=
      - MOVIEPILOT_USER=
      - MOVIEPILOT_PASSWORD=
    restart: unless-stopped
    networks:
      - emby-net

networks:
  emby-net:
    driver: bridge
